### ISSUE TITLE
Missing file when scanning for apps

### ISSUE THREAD

**Issue by ual1n** [alvindimas05/AMDHelper#6]
What can I do to fix this? I had some Adobe programs and after uninstalling, as soon as I try to run the `sudo amdheloper` command, I get this message.

![Screenshot 2024-10-18 at 12 22 39 PM](https://github.com/user-attachments/assets/dab448d0-18d4-40c2-9714-23e2ed35f329)

**Comment by Sooly890** [comment]
I take it that path it's showing you does not exist?

**Comment by luneflu** [comment]
Should be fixed at 109ac88
