### ISSUE TITLE
Missing /usr/local/bin folder

### ISSUE THREAD

**Issue by L1SM0K** [alvindimas05/AMDHelper#7]
![Captura de pantalla 2024-10-19 a la(s) 5 20 10 p m](https://github.com/user-attachments/assets/d6f05398-b75a-44e6-acd8-2d5c089e880a)
I have this issue when trying to install it, even if it says that you can run the command, when you try to run the command it says command not found

**Comment by Sooly890** [comment]
It likely failed to download, just download and extract amdhelper.gz and move the unix executable amdhelper to /usr/local/bin

**Comment by luneflu** [comment]
Sounds like your /usr/local/bin folder is missing. Try create it with
`mkdir /usr/local/bin`

**Comment by luneflu** [comment]
Should be fixed at 019f6d0
